### ISSUE TITLE
Cannot download chapters which include decimal separators

### ISSUE THREAD

**Issue by mateuscv** [frozenpandaman/mangadex-dl#27]
First off. thanks for this handy script.

I've noticed that it's not possible to download chapters which include decimal points, such as "0.01".

The available chapters actually display correctly in the console:

`Available chapters:
 0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.10 ...`

But as the user tries to select one to download, the console displays:
```
Enter chapter(s) to download: 0.02

Done!
```
Yet nothing is actually downloaded. This title also has chapters that are normally numbered (integers starting from 1), and I've had no issues downloading those.

From a little manual debugging I did, it seems that the problem stems from `chapter_num` not receiving the correct value in line 95, though I don't currently understand the API's workings enough to be of any help.

**Comment by frozenpandaman** [comment]
Hey! Yeah, looking at the line you mentioned, it's not just with decimal points, but ones that have a decimal component starting with `0`. So `47.1` would work, but not `47.01`:
https://github.com/frozenpandaman/mangadex-dl/blob/a0c5c5df8e9ac8084c5e3b01940b65a1fe615e71/mangadex-dl.py#L95

The ".0" thing was meant to fix some float-to-string trickiness, but applying it in places other than the end the numerical string (like, in decimals in the middle, in this case!) is what was causing this bug. :D Fixed in v0.2.7! Thanks!
