### ISSUE TITLE
Command-line options for ID/URL and chapters

### ISSUE THREAD

**Issue by Ingvix** [frozenpandaman/mangadex-dl#38]
I find it a bit odd that these aren't implemented already to the point that I'm suspecting it's a deliberate choice to reduce the usage as an automated scheduled downloader. Is that the case or could these be implemented? I was thinking of making the changes myself but would like to confirm if they're acceptable?

**Comment by ArjixWasTaken** [comment]
~~You make 0 sense btw, I suggest rephrasing all of that.~~

**Comment by ArjixWasTaken** [comment]
Oh, I reread the title, and it kinda makes sense now.
It is entirely possible to automate this.

It's just a hacky way.

![image](https://user-images.githubusercontent.com/53124886/131266047-eb649866-4d23-4615-95a3-7e4ce313a6c4.png)
Although...I'm not so sure about the 2nd prompt for the chapters...

Even if it was easy to input data for the episodes into the 2nd prompt...
There is no way to know beforehand how many chapters exist.

So we would need to add an option to download all existing chapters w/o a chapter range.

**Comment by ArjixWasTaken** [comment]
> I find it a bit odd that these aren't implemented already to the point that I'm suspecting it's a deliberate choice to reduce the usage as an automated scheduled downloader. Is that the case or could these be implemented? I was thinking of making the changes myself but would like to confirm if they're acceptable?

> Is that the case or could these be implemented?

It's super easy to implement them, yes.
Actually I had a modified version of this script to download all of the "completed" manga from crunchyroll.
Of course I did not download all of them, but it did download hundreds.

You can see this at https://github.com/ArjixWasTaken/mangadex-dl/blob/download-hoarder/mangadex-dl.py
Of course since I designed it to download all of the completed manga from mangadex, you can't specify a specific manga or chapter id.

**Comment by Ingvix** [comment]
> It is entirely possible to automate this.
> 
> It's just a hacky way.

I know it's possible but as I see it the current way it's implemented curtainly doesn't encourage doing it. 
> Although...I'm not so sure about the 2nd prompt for the chapters...

> 
> Even if it was easy to input data for the episodes into the 2nd prompt...
> There is no way to know beforehand how many chapters exist.
> 
> So we would need to add an option to download all existing chapters w/o a chapter range.

You got me there. I didn't think that one through. There's certainly room for improvements that would not take too much effort to implement but I'd like to get a confirmation from @frozenpandaman if they find such changes desirable as to whether I should plan to make a PR.

**Comment by ArjixWasTaken** [comment]
> but I'd like to get a confirmation from @frozenpandaman if they find such changes desirable as to whether I should plan to make a PR.

Uhh, even if those changes are not desirable, @frozenpandaman can just close the PR.
No need to consult with him, he is the one that decides if it will get merged either way.

**Comment by Ingvix** [comment]
That's true though there's also the point that if he's willing to make the changes himself I don't have bother making them. ¯\\\_(ツ)\_\/¯

**Comment by ArjixWasTaken** [comment]
It's literally like 5-8 extra lines of code. ¯\\\_(ツ)_/¯

**Comment by frozenpandaman** [comment]
Hi @Ingvix! Thanks for all the interest here. :) Sorry, I have a lot of stuff in my life right now and not much to devote to this project. Also just not reading really any manga currently haha.

>I'm suspecting it's a deliberate choice to reduce the usage as an automated scheduled downloader. Is that the case or could these be implemented?

Not super deliberate, but I guess it wasn't the intended use case – informed by my reading habits/methods, haha. I just envisioned users running this manually before wanting to read some chapters or catch up since the last time they checked in (which I do using a simple image viewer for on-disc files).

I'd say sure – if you want to automate it a bit (though please do monitor it so it doesn't accidentally end up hammering servers, especially if APIs change) you can pass in successive input using bash's `read` function to emulate the user input at both of the prompts…

>So we would need to add an option to download all existing chapters w/o a chapter range.

…but I think this is right, it's only possible if there's an "all" option that downloads all available chapters, e.g. if 1 through 30 are available, you could just type in `all` instead of `1-30`. Or at least that'd make things a lot easier.

It seems you're pretty eager and willing to create a PR, @ArjixWasTaken, haha. If you add in this option, and change the I/O to be like this:
```
Type "all" to download all available chapters.
Or, enter specific chapter(s) to download: 
```
I'll approve the PR! Please make this and only this one PR, and any other ideas you may have separate ones, for the sake of clarity. Just @ me so it doesn't get lost, I got like 20 emails from all the comments on this repo the past few days 😅

**Comment by frozenpandaman** [comment]
Closing due to lack of any new activity/input.

If anyone does want to go ahead and add functionality for easily downloading "all" chapters, as mentioned above, do feel free.
